# version: '3'
# services:   
#     # mysql:
#     #     build:
#     #         context: ./mysql  # Directory containing Dockerfile.mysql
#     #     ports:
#     #         - "3366:3306"
#     #     environment:
#     #         MYSQL_ROOT_PASSWORD: Ouattwac@4321
#     #         MYSQL_DATABASE: payment_records
#     django:
#         build: 
#             context: .
#         ports:
#             - "8000:8000"
#         # depends_on:
#         #     - kafka
#         volumes:
#             - .:/paymentsettlementapp  # Mount your Django project directory into the container

version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/django
    
    image: app:djangoports:
      - 8000:8000
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db 
  db:
    image: mysql:8.0
    environment:
        - MYSQL_DATABASE=payment_records
        - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data/mysql/db:/var/lib/mysql
