# Generated by Django 4.2.5 on 2023-09-26 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment_app', '0004_delete_settlement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_settled', models.BooleanField(default=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_app.payment')),
            ],
        ),
    ]
