# Generated by Django 4.2.5 on 2023-09-26 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0003_alter_settlement_payment_settled'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settlement',
        ),
    ]
